### ISSUE TITLE
Global: Main Navigation

### ISSUE THREAD

**Issue by florianschumacher** [florianschumacher/capstone#10]
## Value statement - a requirement, not a solution
As a **User** 
I need **the main navigation** 
so that **i can navigate from page to page** 

## 
![image](https://user-images.githubusercontent.com/48018310/99723425-74f9b800-2ab2-11eb-88b8-c61bf731a69c.png)

## Acceptance criteria
- [ ] All items are clickable
- [ ] Click on items loads the fitting page
- [ ] i am able to navigate from any of the website to another
- [ ] the element is on all pages available
- [ ] the element and its children stay on position
- [ ] current active states are hichlighted

## Tasks
- [ ] program navigation
- [ ] create dummy content to test functionality

## Size
(small, medium, large)
