### ISSUE TITLE
Global: Search

### ISSUE THREAD

**Issue by florianschumacher** [florianschumacher/capstone#11]
## Value statement - a requirement, not a solution
As a **user** 
I need **the search** 
so that **look for locations and activities** 

## Description (Text, Scribble, Wireframe, Design)
![image](https://user-images.githubusercontent.com/48018310/99787222-c2603e80-2b1f-11eb-88da-18e736cff298.png)

## Acceptance criteria
- [ ] text field is editable
- [ ] search field is available on the responding pages
- [ ] text can be entered
- [ ] pressing enter or the search icon sends a search request and opens the search view
- [ ] field object is fixed

## Tasks
- [ ] create list / array
- [ ] create querry
- [ ] create form

## Size
large
