### ISSUE TITLE
Map: Map view

### ISSUE THREAD

**Issue by florianschumacher** [florianschumacher/capstone#12]
## Value statement - a requirement, not a solution
As a **user** 
I need **the presentation of a map ** 
so that **view the local surroundings** 

## Description (Text, Scribble, Wireframe, Design)
![image](https://user-images.githubusercontent.com/48018310/99788721-cdb46980-2b21-11eb-9870-bdd9ec633b34.png)

## Acceptance criteria
- [ ] map shows current location
- [ ] map shows special places
- [ ] map can be moved
- [ ] map shows location when searched for

## Tasks
- [ ] connect map api
- [ ] connect location- db with map api

## Size
large
