### ISSUE TITLE
User administration: Global Profile Icon

### ISSUE THREAD

**Issue by florianschumacher** [florianschumacher/capstone#13]
## Value statement - a requirement, not a solution
As a **user** 
I need **user icon** 
so that **i know i am logged in** 

## Description (Text, Scribble, Wireframe, Design)
![image](https://user-images.githubusercontent.com/48018310/99789486-f38e3e00-2b22-11eb-88ff-71a9541e2d89.png)

## Acceptance criteria
- [ ] User profile picture is visible
- [ ] click on user profile icon opens profile page
- [ ] element is fixed
- [ ] element is visible on all pages, except on the profile page

## Tasks
- [ ] create icon
- [ ] get data from user administration

## Size
small
