### ISSUE TITLE
Lists: Import Data via API

### ISSUE THREAD

**Issue by florianschumacher** [florianschumacher/capstone#14]
## Value statement - a requirement, not a solution
As a **user** 
I need **a list on ~~available spot and activities~~ healthy recipes** 
so that **i am able to get an overview on healthy recipes** 

## Description (Text, Scribble, Wireframe, Design)
![image](https://user-images.githubusercontent.com/48018310/99790287-2d137900-2b24-11eb-948a-025ae95e778d.png)

## Acceptance criteria
- [x] existing recipes will be displayed within a list
- ~~elements are ordered responding range to user location (tbd)~~
- [x] list is scroll able

## Tasks
- [x] get ~~location~~ food data
- [x] visualize data

## Size
large
