### ISSUE TITLE
List: Filter

### ISSUE THREAD

**Issue by florianschumacher** [florianschumacher/capstone#15]
## Value statement - a requirement, not a solution
As a **user** 
I need **to filter** 
so that **i can focus an results i am interested in** 

## Description (Text, Scribble, Wireframe, Design)
![image](https://user-images.githubusercontent.com/48018310/99790867-0570e080-2b25-11eb-9bc9-51f18d41bd87.png)

## Acceptance criteria
- [ ] Filters can be clicked
- [ ] Filters can be swiped so i can use filters out of screen
- [ ] i can use multiple filters
- [ ]  i can reset filters
- [ ] applied filters change the list results
- [ ] reset filters switched results to default state

## Tasks
- [ ] create filter

## Size
large
