### ISSUE TITLE
Detailpage: Header

### ISSUE THREAD

**Issue by florianschumacher** [florianschumacher/capstone#16]
## Value statement - a requirement, not a solution
As a **user** 
I need **an Header** 
so that **i know which location i am looking on** 

## Description (Text, Scribble, Wireframe, Design)
![image](https://user-images.githubusercontent.com/48018310/99791849-88df0180-2b26-11eb-8e8d-117573288ecb.png)

## Acceptance criteria
- [ ] header contains profile icon, h1 title and Back- Button
- [ ] headline corresponds to content
- [ ] Back- Button is clickable

## Tasks
- [ ] create header
- [ ] create back button

## Size
medium
