### ISSUE TITLE
Detailpage: Gallery

### ISSUE THREAD

**Issue by florianschumacher** [florianschumacher/capstone#17]
## Value statement - a requirement, not a solution
As a **user** 
I need **gallery** 
so that **i can see pictures** 

## Description (Text, Scribble, Wireframe, Design)
![image](https://user-images.githubusercontent.com/48018310/99792349-42d66d80-2b27-11eb-9acb-8b92635c5d1e.png)

## Acceptance criteria
- [ ] shows images
- [ ] can be swiped to show additional images
- [ ] images can be enlarged and normalized
- [ ] user can click on arrows to swipe but does not have to

## Tasks
- [ ] get data
- [ ] create gallery element

## Size
medium
