### ISSUE TITLE
Share

### ISSUE THREAD

**Issue by florianschumacher** [florianschumacher/capstone#18]
## Value statement - a requirement, not a solution
As a **user)** 
I need **the ability to share locations** 
so that **other users can see the location as well** 

## Description (Text, Scribble, Wireframe, Design)
![image](https://user-images.githubusercontent.com/48018310/99796805-6bae3100-2b2e-11eb-9b30-b4a05886d959.png)

## Acceptance criteria
- [ ] click opens share dialog
- [ ] share via facebook, mail, whatsapp

## Tasks
- [ ] implement social share api

## Size
small
