### ISSUE TITLE
Route Export

### ISSUE THREAD

**Issue by florianschumacher** [florianschumacher/capstone#19]
## Value statement - a requirement, not a solution
As a **user** 
I need **the route** 
so that **reach my destination** 

## Description (Text, Scribble, Wireframe, Design)
![image](https://user-images.githubusercontent.com/48018310/99797344-5f76a380-2b2f-11eb-9124-af74de573256.png)

## Acceptance criteria
- [ ] click on route opens destination export
- [ ] can be used within google maps and apple cards

## Tasks
- [ ] get map and location data
- [ ] create data export

## Size
large
