### ISSUE TITLE
Bookmark

### ISSUE THREAD

**Issue by florianschumacher** [florianschumacher/capstone#20]
## Value statement - a requirement, not a solution
As a **user** 
I need **to save locations** 
so that **can them recall them at any time** 

## Description (Text, Scribble, Wireframe, Design)
![image](https://user-images.githubusercontent.com/48018310/99797609-dca21880-2b2f-11eb-9e03-91d356901b63.png)

## Acceptance criteria
- [ ] per default inactive
- [ ] when clicked shown as active (bookmarked)
- [ ] page is saved to bookmarks- list

## Tasks
- [ ] save location to user

## Size
large
