### ISSUE TITLE
Content- Toggle

### ISSUE THREAD

**Issue by florianschumacher** [florianschumacher/capstone#21]
## Value statement - a requirement, not a solution
As a **user** 
I need **want to switch through all information** 
so that **i am able to see, if a place is interesting** 

## Description (Text, Scribble, Wireframe, Design)
![image](https://user-images.githubusercontent.com/48018310/99797763-268afe80-2b30-11eb-8765-d9879eb54321.png)

## Acceptance criteria
- [ ] toggle between different offers
- [ ] active toggle is highlighted
- [ ] content switches regarding to selection

## Tasks
- [ ] create toggle
- [ ] connect data to content-/toggle elements

## Size
large
